### ISSUE TITLE
Developer Portal Section Missing on Home Page

### ISSUE THREAD

**Issue by zyad87** [SarahJumaiah/Swaef#3]
The Developer Portal section is currently missing from the home page. This section is essential for guiding developers to resources, documentation, and API access for integrating with our platform. It should be visible and accessible to ensure developers can easily navigate to the portal.

Expected Behavior: The home page should display a dedicated section or link that directs users to the Developer Portal.

Steps to Reproduce:

Go to the home page.
Look for the Developer Portal section or link.
Notice that it is not currently displayed.
Suggested Solution: Please add a clear section or button on the home page that links directly to the Developer Portal.

**Comment by SarahJumaiah** [comment]
The issue has been resolved. The Developer Portal section is now visible on the home page as requested. We have added a dedicated section with a clear button that directs users straight to the Developer Portal, making it easy for developers to find resources, documentation, and API access for seamless integration with our platform.

**Comment by zyad87** [comment]
Great to hear the issue has been resolved! Thank you for adding the Developer Portal section to the home page. The clear button directing users to the portal will definitely improve navigation, making it much easier for developers to access all necessary resources, documentation, and API integrations. This enhancement will be a big help for our developer community.

Thanks again for the prompt fix!

**Comment by zyad87** [comment]
Great to hear the issue has been resolved! Thank you for adding the Developer Portal section to the home page. The clear button directing users to the portal will definitely improve navigation, making it much easier for developers to access all necessary resources, documentation, and API integrations. This enhancement will be a big help for our developer community.

Thanks again for the prompt fix!
